// export const LOGOUT = 'LOGOUT';
// export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const actionTypes = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',

  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',

  SET_AUTH_MODAL_OPEN: 'SET_MODAL_OPEN',
  SET_AUTH_MODAL_CLOSE:'SET_AUTH_MODAL_CLOSE',
  
};
